export const types = {
  AUTH_FAIL: 'AUTH_FAIL',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_START: 'AUTH_START',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  SET_AUTH_REDIRECT_PATH: 'SET_AUTH_REDIRECT_PATH',
  UPDATE_AUTH_INPUT: 'UPDATE_AUTH_INPUT'
}