export const types = {
    SET: {
        MINIFIGS: 'SET.MINIFIGS',
        STATISTICS: 'SET.STATISTICS',
        TAGS_AND_CHARACNAMES: 'SET.TAGS_AND_CHARACNAMES',
        POSSESION_TO_ALL: 'SET.POSSESION_TO_ALL'
    },
    TOGGLE: {
        POSSESSION: 'TOOGLE.POSSESSION'
    },
    DELETE: {
        MINIFIG: 'DELETE.MINIFIG'
    },
    ADD_OR_EDIT_A_MINIFIG: 'ADD_OR_EDIT_A_MINIFIG'
}